=== jonesgc/3rdYr_ATWD_Assignment/atwd1_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="atwd1">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student" type="studentType"/>
        <xs:element name="assignment" type="assignmentType"/>
      </xs:sequence>
      <xs:attribute name="code" use="required" fixed="UFCFX3-15-3"/>
      <xs:attribute name="name" use="required" fixed="Advanced Topics in Web Development"/>
      <xs:attribute name="year" use="required" fixed="2018/19"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="studentType">
    <xs:attribute name="sno" use="required" type="snoType"/>
    <xs:attribute name="un" use="required" type="unType"/>
    <xs:attribute name="surname" use="required" type="surnameType"/>
    <xs:attribute name="prog" use="required" type="progType"/>
  </xs:complexType>

  <xs:complexType name="assignmentType">
    <xs:sequence>
      <xs:element minOccurs="3" maxOccurs="3" ref="component"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="component">
    <xs:alternative test="@id='A'" type="cTypeA"/>
    <xs:alternative test="@id='B'" type="cTypeB"/>
    <xs:alternative test="@id='C'" type="cTypeC"/>
    <xs:alternative type="xs:error"/>
  </xs:element>

  <xs:complexType name="cTypeA">
    <xs:sequence>
      <xs:element name="tests" maxOccurs="1" type="testsType"/>
      <xs:element name="data" maxOccurs="1" type="dataType"/>
      <xs:element name="code" maxOccurs="1" type="codeType"/>
      <xs:element name="comment" maxOccurs="1" type="commentType"/>
    </xs:sequence>
    <xs:attribute name="id" use="required" fixed="A"/>
    <xs:attribute name="name" use="required" fixed="Application"/>
  </xs:complexType>

  <xs:complexType name="cTypeB">
    <xs:sequence>
      <xs:element name="code" maxOccurs="1" type="codeType"/>
      <xs:element name="form" maxOccurs="1" type="urlType"/>
      <xs:element name="comment" maxOccurs="1" type="commentType"/>
    </xs:sequence>
    <xs:attribute name="id" use="required" fixed="B"/>
    <xs:attribute name="name" use="required" fixed="Post, Put &amp; Delete implementation"/>
  </xs:complexType>

  <xs:complexType name="cTypeC">
    <xs:sequence>
      <xs:element name="eval" minOccurs="1" type="evalType"/>
    </xs:sequence>
    <xs:attribute name="id" use="required" fixed="C"/>
    <xs:attribute name="name" use="required" fixed="Critical Evaluation"/>
  </xs:complexType>

  <xs:complexType name="testsType">
    <xs:sequence>
      <xs:element maxOccurs="8" name="test" type="testType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="testType">
    <xs:simpleContent>
      <xs:extension base="urlType">
        <xs:attribute name="id" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:integer">
              <xs:pattern value="[0-9]"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="response" use="required">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:pattern value="(xml|json)"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="type" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="dataType">
    <xs:sequence>
      <xs:element name="rates_file" type="urlType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="urlType">
    <xs:restriction base="xs:anyURI">
      <xs:pattern
        value="http://isa.cems.uwe.ac.uk/~[a-z0-9]{1,5}\-[a-z0-9]{2,12}/atwd1/assignment/.+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="fileType">
    <xs:simpleContent>
      <xs:extension base="urlType">
        <xs:attribute name="type" use="required" type="xs:NCName"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="codeType">
    <xs:choice>
      <xs:sequence>
        <xs:element name="file" maxOccurs="8" type="fileType"/>
      </xs:sequence>
    </xs:choice>
  </xs:complexType>

  <xs:simpleType name="evalType">
    <xs:restriction base="xs:string">
      <xs:minLength value="40"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="commentType">
    <xs:restriction base="xs:string">
      <xs:minLength value="40"/>
      <xs:maxLength value="200"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="unType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[a-z0-9]{1,5}\-[a-z0-9]{2,12}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="surnameType">
    <xs:restriction base="xs:string">
      <xs:minLength value="2"/>
      <xs:maxLength value="18"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="fileType">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:anyURI">
          <xs:attribute name="type" use="required" type="xs:NCName"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:simpleType name="snoType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="16016225"/>
      <xs:enumeration value="16021337"/>
      <xs:enumeration value="15010844"/>
      <xs:enumeration value="18021822"/>
      <xs:enumeration value="15000863"/>
      <xs:enumeration value="18025849"/>
      <xs:enumeration value="16022950"/>
      <xs:enumeration value="15042374"/>
      <xs:enumeration value="15021296"/>
      <xs:enumeration value="18026323"/>
      <xs:enumeration value="18026343"/>
      <xs:enumeration value="15042351"/>
      <xs:enumeration value="14024744"/>
      <xs:enumeration value="16036844"/>
      <xs:enumeration value="16007716"/>
      <xs:enumeration value="16013010"/>
      <xs:enumeration value="16014582"/>
      <xs:enumeration value="16016966"/>
      <xs:enumeration value="16044260"/>
      <xs:enumeration value="15036210"/>
      <xs:enumeration value="18025886"/>
      <xs:enumeration value="18025877"/>
      <xs:enumeration value="18044808"/>
      <xs:enumeration value="18025848"/>
      <xs:enumeration value="17035315"/>
      <xs:enumeration value="16016703"/>
      <xs:enumeration value="16028370"/>
      <xs:enumeration value="14003886"/>
      <xs:enumeration value="15034088"/>
      <xs:enumeration value="16006545"/>
      <xs:enumeration value="16009817"/>
      <xs:enumeration value="16030652"/>
      <xs:enumeration value="14041505"/>
      <xs:enumeration value="14014276"/>
      <xs:enumeration value="18036591"/>
      <xs:enumeration value="16004897"/>
      <xs:enumeration value="18019884"/>
      <xs:enumeration value="16025186"/>
      <xs:enumeration value="16033679"/>
      <xs:enumeration value="15029199"/>
      <xs:enumeration value="15031390"/>
      <!-- test case -->
      <xs:enumeration value="99999999"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="progType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="BSc (Hons) Digital Media"/>
      <xs:enumeration value="BSc (Hons) Information Technology"/>
      <xs:enumeration value="BSc (Hons) Information Technology (Dual)"/>
      <xs:enumeration value="BSc(Hons) Software Engineering for Business"/>
      <xs:enumeration value="BSc(Hons) Multimedia Technology"/>
      <xs:enumeration value="BSc (Hons) Digital &amp; Technology Solutions"/>
      <xs:enumeration value="BSc (Hons) Computing"/>
      <xs:enumeration value="BSc (Hons) Computer Science"/>      
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== jonesgc/3rdYr_ATWD_Assignment/16036844.xml
<?xml version="1.0" encoding="UTF-8"?>
<atwd1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.cems.uwe.ac.uk/~p-chatterjee/2018-19/modules/atwd1/assignment/atwd1_schema.xsd" code="UFCFX3-15-3" name="Advanced Topics in Web Development" year="2018/19">
    <student sno="16036844" un="g45-jones" surname="Jones" prog="BSc (Hons) Digital Media"/>
    <assignment>
        <component id="A" name="Application">
            <tests>
                <!--
 
                 Note that you should only need to edit the '~a-student' value 
                 to your own username to make these tests work for your application.
                
-->
                <!--  convert 100.00 GBP to INR and return XML  -->
                <test id="1" response="xml" type="sucess">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/?from=GBP&to=INR&amnt=100.00&format=xml
                </test>
                <!--  convert 85.75 from USD to EUR and return JSON  -->
                <test id="2" response="json" type="sucess">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/?from=USD&to=EUR&amnt=85.75.00&format=json
                </test>
                <!--
 redo test 1 but leave out 'format' parameter - should return XML by default 
-->
                <test id="3" response="xml" type="sucess">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/?from=GBP&to=INR&amnt=100.00
                </test>
                <!--
 error 1000: Required parameter is missing - the 'from' parameter is missing 
-->
                <test id="4" response="xml" type="error 1000">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/?to=EUR&amnt=100.00&format=xml
                </test>
                <!--
 error 1100: Parameter not recognized - the 'to' parameter is missing the 'o' (return json) 
-->
                <test id="5" response="json" type="error 1100">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/?from=USD&t=EUR&amnt=100.00&format=json
                </test>
                <!--
 error 1200: Currency type not recognised - the 'from' value is 'YYY') 
-->
                <test id="6" response="json" type="error 1200">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/?from=YYY&to=EUR&amnt=18.85&format=xml
                </test>
                <!--
 error 1300: Currency amount must be a decimal number - the 'amnt' value is non-decimal) 
-->
                <test id="7" response="xml" type="error 1300">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/?from=USD&to=EUR&amnt=NaN&format=xml
                </test>
                <!--
 error 1400: Format must be xml or json - the 'format' value is 'ZZZ') 
-->
                <test id="8" response="xml" type="error 1400">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/?from=USD&to=EUR&amnt=19.20&format=ZZZ
                </test>
            </tests>
            <data>
                <rates_file>
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/curData.xml
                </rates_file>
            </data>
            <code>
                <file type="main">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/docs/index.phps
                </file>
                <!--  You can add uo to 7 addtional url's here  -->
                <file type="config">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/docs/config.phps
                </file>
                <file type="errorHandling">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/docs/generateError.phps
                <file type="externalAPI">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/docs/curDataMonitor.phps
                </file>
                <file type="GET">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/docs/currGet.phps
                </file>
            </code>
            <comment>This was easy-peasy. Did it in my sleep.</comment>
        </component>
        <component id="B" name="Post, Put & Delete implementation">
            <code>
                <file type="POST">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/docs/currPost.phps
                </file>
                <file type="PUT">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/docs/currPut.phps
                </file>
                <file type="DEL">
                    http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/docs/currDelete.phps
                </file>
            </code>
            <!--  interface form  -->
            <form>
                http://isa.cems.uwe.ac.uk/~g45-jones/atwd1/assignment/client/client.html
            </form>
            <comment>
                A responsive form and easy code - again far too easy. Blimey, is this first year stuff?
            </comment>
        </component>
        <component id="C" name="Critical Evaluation">
            <eval>
                <![CDATA[
<p>Can be up to 500 words and can include HTML5 or Markdown markup</p>
]]>
            </eval>
        </component>
    </assignment>
</atwd1>
<!--  ATWD1 assignment XML submission File, 2018  -->
<!--  author: prakash.chatterjee@uwe.ac.uk  -->
